### ISSUE TITLE
Download location of installation files during setup.exe configure step

### ISSUE THREAD

**Issue by ToolingModus** [mallockey/Install-Office365Suite#13]
Hi,

I would like to know where the downloaded Microsoft 365 installation files are stored during the setup.exe configure step.
Would anyone know what the location is of these files?

Best regards

**Comment by mallockey** [comment]
That would be defined in the `$OfficeInstallDownloadPath` variable:

![Screenshot 2023-04-26 172727](https://user-images.githubusercontent.com/25836748/234707016-2248e06b-263e-4d96-8bb0-0ddd7b5bb209.png)

**Comment by ToolingModus** [comment]
Thanks for replying.

But these are not the actual office installation files. The office installation files would be a couple gigabytes in total.
If you would first do a Download and then Configure command, then you would know the actual directory with the installation files. But if you only use the Configure command..?

**Comment by ToolingModus** [comment]
I will close this issue. I may look into this later when it is important enough for me to spend the time to figure it out.
