### ISSUE TITLE
Script is outdated now that O365 has been renamed Microsoft 365 Apps

### ISSUE THREAD

**Issue by gak1234** [mallockey/Install-Office365Suite#3]
Great script! However, it installs an outdated version of O365. The newer builds have been renamed to "Microsoft 365 Apps" and the editions are Enterprise (formerly proplus) and Business (formerly businesspremium).

Easy fix! They still refer to the product editions internally in the XML as they did before (O365ProPlus, etc).

Also noticed that a few of your documentations have minor mistakes:

-EnabledUpdates                        should be       -EnableUpdates     
-OfficeInstallerDownloadPath     should be        -OfficeInstallDownloadPath

Nice work, I really find this script useful with ConnectWise Automate and similar RMM tools.

**Comment by mallockey** [comment]
Thanks for the feedback!

Hmm I still only see O365ProPlusRetail and O365BusinessRetail according to the Office Customization Tool site though. What should I be changing the OfficeEdition to now?

From the latest version of the script I see the parameters specified as EnableUpdates and OfficeInstallDownloadPath, not sure what needs to be changed.

Thanks again!

**Comment by mallockey** [comment]
Closing due to lack of response.
