### ISSUE TITLE
Suggestion: offer to download the xml config file from an URL

### ISSUE THREAD

**Issue by schittli** [mallockey/Install-Office365Suite#5]
Hello
**thank you very much fur sharing your great work!**

I just have a probably small suggestion:
Microsoft offers to get a link **(1)** for XML config files:
![image](https://user-images.githubusercontent.com/8282673/180649754-73331d27-30a4-4096-8951-278fb15b7988.png)

Therefore, it would be awesome if `Install-Office365Suite.ps1` would offer to download the XML config file from a provided URL, use it and delete it afterward.

Thanks a lot, kind regards,
Thomas

**Comment by mallockey** [comment]
This is a good idea! I'll create a feature for this.

**Comment by mallockey** [comment]
Hi @schittli ,  I was just reviewing the docs for the URL based XML file and it looks like this should actually already work now that the [this bug ](https://github.com/mallockey/Install-Office365Suite/issues/6) has been resolved.

According to the [docs](https://docs.microsoft.com/en-us/deployoffice/admincenter/overview-office-customization-tool), it looks like as long as you pass the URL to the setup.exe /configure parameter it should just work. 

`When running the Office Deployment Tool, you refer to the cloud-based configuration file by including the link in quotes. To deploy with the ODT, for example, use setup.exe /configure "link".`

And that's what the script does on line 152: 
`$Silent = Start-Process "$OfficeInstallDownloadPath\Setup.exe" -ArgumentList "/configure $ConfigurationXMLFile" -Wait -PassThru`

Unfortunately, I don't have an MS account to test this out with the URL from the office config site but this should work so I'll close this for now. Feel free to open up another issue if it still doesn't work.
