### ISSUE TITLE
`-ConfigurationXMLFile`: Does not work, will probably always set to `"$OfficeInstallDownloadPath\OfficeInstall.xml"`

### ISSUE THREAD

**Issue by schittli** [mallockey/Install-Office365Suite#6]
Hello

I tried `Install-Office365Suite.ps1` and the `-ConfigurationXMLFile` parameter, but it never worked.

I guess, that this is a bug in Line 124:

`$ConfigurationXMLFile = "$OfficeInstallDownloadPath\OfficeInstall.xml"`

It looks like the `$ConfigurationXMLFile` Parameter gets always overwritten.

Thanks a lot, kind regards,
Thomas

**Comment by mallockey** [comment]
Hey @schittli ! Thanks for pointing this out. I'm not home now so I can't test this but I think to fix this I need to just move mine 124 into the if statement on line 113. I'll push up a fix once I'm back, feel free to push up a PR if you'd like.

**Comment by mallockey** [comment]
This is resolved. Thanks again for pointing this out!
