### ISSUE TITLE
Flags not working

### ISSUE THREAD

**Issue by HughisaName** [mallockey/Install-Office365Suite#7]
Hi Mallockey,

I've tried installing o365 using the script, i've tried many times with a couple of different machines and seems like some flags dont work for me. For eg i've tried specifying channel as monthly however i get Current channel all the time and pin to taskbar flag doesnt work either.

**Comment by HughisaName** [comment]
Seems like the Monthly Channel is now called MonthlyEnterprise

**Comment by mallockey** [comment]
Hi @HughisaName ! 

Thanks for pointing this out, I think I need a more proactive process on knowing when the Microsoft updates the properties but for now, I made this [PR](https://github.com/mallockey/Install-Office365Suite/pull/8) to update the channels to the current ones.

As for pin to taskbar, I've been told that only works on Windows 7. I 'll open up another MR to remove that option.

**Comment by HughisaName** [comment]
I am also trying to include a parameter to include project and visio, but i keep getting issues with creating xml. DO you  mind taking a look?

Where can i send code block
________________________________

**Comment by mallockey** [comment]
Added Visio and Project parameter [here](https://github.com/mallockey/Install-Office365Suite/pull/9)
